services:
  mockmusicinfo:
    build:
      context: musicinfo-mock
      dockerfile: ./Dockerfile
    ports:
      - "3256:3256"

  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/postgresql:/var/lib/postgresql
